M$ = "GFE-FGGG"

SUB SONIDO
 FOR J = 4000 TO 2000 STEP -60
   SOUND J, .3
 NEXT J
 FOR J = 120 TO 80 STEP -5
   SOUND J, .5
 NEXT J
END SUB

CLS
CALL SONIDO


REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI001.TUB
LOCATE 2,7
COLOR 0,7
PRINT "здддбдддбдддбдддбдддбдддбдддбддд©";
LOCATE 3,7
PRINT "Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё";
LOCATE 4,7
PRINT "цдддедддедддедддедддедддедддеддд╢";
LOCATE 5,7
PRINT "Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё";
LOCATE 6,7
PRINT "цдддедддедддадддадддадддадддаддды";
LOCATE 7,7
PRINT "Ё   Ё   Ё";
LOCATE 8,7
PRINT "цдддеддд╢";
LOCATE 9,7
PRINT "Ё   Ё   Ё";
LOCATE 10,7
PRINT "цдддеддд╢";
LOCATE 11,7
PRINT "Ё   Ё   Ё";
LOCATE 12,7
PRINT "цдддеддд╢";
LOCATE 13,7
PRINT "Ё   Ё   Ё";
LOCATE 14,7
PRINT "цдддеддд╢";
LOCATE 15,7
PRINT "Ё   Ё   Ё";
LOCATE 16,7
PRINT "цдддеддд╢";
LOCATE 17,7
PRINT "Ё   Ё   Ё";
LOCATE 18,7
PRINT "цдддеддд╢";
LOCATE 19,7
PRINT "Ё   Ё   Ё";
LOCATE 20,7
PRINT "цдддедддедддбдддбдддбдддбдддбдддбдддбдддбдддбдддбдддбдддбдддбддд©";
LOCATE 21,7
PRINT "Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё";
LOCATE 22,7
PRINT "цдддедддедддедддедддедддедддедддедддедддедддедддедддедддедддеддд╢";
LOCATE 23,7
PRINT "Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё   Ё";
LOCATE 24,7
PRINT "юдддадддадддадддадддадддадддадддадддадддадддадддадддадддадддаддды";

CALL SONIDO


REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI002.TUB
LOCATE 8,17
COLOR 0,7
PRINT "здддбдддбддд©";
LOCATE 9,17
PRINT "Ё   Ё   Ё   Ё";
LOCATE 10,17
PRINT "цдддедддеддд╢";
LOCATE 11,17
PRINT "Ё   Ё";
LOCATE 11,25
PRINT "Ё   Ё";
LOCATE 12,17
PRINT "цдддедддеддд╢";
LOCATE 13,17
PRINT "Ё   Ё   Ё   Ё";
LOCATE 14,17
PRINT "цдддедбдадбды";
LOCATE 15,17
PRINT "Ё   Ё";
LOCATE 15,23
PRINT "Ё   Ё";
LOCATE 16,17
PRINT "цддд╢";
LOCATE 16,23
PRINT "юдбдад©";
LOCATE 17,17
PRINT "Ё   Ё";
LOCATE 17,25
PRINT "Ё   Ё";
LOCATE 18,17
PRINT "юддды";
LOCATE 18,25
PRINT "юддды";

CALL SONIDO

REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI003.TUB
LOCATE 8,31
COLOR 0,7
PRINT "зддд©";
LOCATE 8,39
PRINT "зддд©";
LOCATE 9,31
PRINT "Ё   Ё";
LOCATE 9,39
PRINT "Ё   Ё";
LOCATE 10,31
PRINT "цддд╢";
LOCATE 10,39
PRINT "цддд╢";
LOCATE 11,31
PRINT "Ё   Ё";
LOCATE 11,39
PRINT "Ё   Ё";
LOCATE 12,31
PRINT "цддд╢";
LOCATE 12,39
PRINT "цддд╢";
LOCATE 13,31
PRINT "Ё   Ё";
LOCATE 13,39
PRINT "Ё   Ё";
LOCATE 14,31
PRINT "цддд╢";
LOCATE 14,39
PRINT "цддд╢";
LOCATE 15,31
PRINT "Ё   Ё";
LOCATE 15,39
PRINT "Ё   Ё";
LOCATE 16,31
PRINT "цдддедддеддд╢";
LOCATE 17,31
PRINT "Ё   Ё   Ё   Ё";
LOCATE 18,31
PRINT "юдддадддаддды";

CALL SONIDO

REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI004.TUB
LOCATE 8,45
COLOR 0,7
PRINT "здддбдддбддд©";
LOCATE 9,45
PRINT "Ё   Ё   Ё   Ё";
LOCATE 10,45
PRINT "цдддедддаддды";
LOCATE 11,45
PRINT "Ё   Ё";
LOCATE 12,45
PRINT "цддд╢";
LOCATE 13,45
PRINT "Ё   Ё";
LOCATE 14,45
PRINT "цддд╢";
LOCATE 15,45
PRINT "Ё   Ё";
LOCATE 16,45
PRINT "цдддедддбддд©";
LOCATE 17,45
PRINT "Ё   Ё   Ё   Ё";
LOCATE 18,45
PRINT "юдддадддаддды";

CALL SONIDO

REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI005.TUB
LOCATE 8,59
COLOR 0,7
PRINT "здддбдддбддд©";
LOCATE 9,59
PRINT "Ё   Ё   Ё   Ё";
LOCATE 10,59
PRINT "юдддедддеддды";
LOCATE 11,63
PRINT "Ё   Ё";
LOCATE 12,63
PRINT "цддд╢";
LOCATE 13,63
PRINT "Ё   Ё";
LOCATE 14,63
PRINT "цддд╢";
LOCATE 15,63
PRINT "Ё   Ё";
LOCATE 16,59
PRINT "здддедддеддд©";
LOCATE 17,59
PRINT "Ё   Ё   Ё   Ё";
LOCATE 18,59
PRINT "юдддадддаддды";

CALL SONIDO

REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI006.TUB
LOCATE 3,8
COLOR 0,7
PRINT " C ";
LOCATE 3,12
PRINT " A ";
LOCATE 3,16
PRINT " T ";
LOCATE 3,20
PRINT " A ";
LOCATE 3,24
PRINT " L ";
LOCATE 3,28
PRINT " U ";
LOCATE 3,32
PRINT " ╔ ";
LOCATE 3,36
PRINT " A ";
LOCATE 5,8
PRINT " A ";
LOCATE 5,12
PRINT " C ";
LOCATE 5,16
PRINT " U ";
LOCATE 5,20
PRINT " S ";
LOCATE 5,24
PRINT " A ";
LOCATE 5,28
PRINT "╠╠╠";
LOCATE 5,32
PRINT " U ";
LOCATE 5,36
PRINT " N ";
LOCATE 7,8
PRINT " S ";
LOCATE 7,12
PRINT " I ";
LOCATE 9,8
PRINT " A ";
LOCATE 9,12
PRINT " D ";
LOCATE 9,18
PRINT " D ";
LOCATE 9,22
PRINT " I ";
LOCATE 9,26
PRINT " A ";
LOCATE 9,32
PRINT " M ";
LOCATE 9,40
PRINT " A ";
LOCATE 9,46
PRINT " S ";
LOCATE 9,50
PRINT " A ";
LOCATE 9,54
PRINT " L ";
LOCATE 9,60
PRINT " E ";
LOCATE 9,64
PRINT " G ";
LOCATE 9,68
PRINT " O ";
LOCATE 11,8
PRINT "╠╠╠";
LOCATE 11,12
PRINT " O ";
LOCATE 11,18
PRINT " E ";
LOCATE 11,26
PRINT " ╔ ";
LOCATE 11,32
PRINT " A ";
LOCATE 11,40
PRINT " M ";
LOCATE 11,46
PRINT " O ";
LOCATE 11,64
PRINT " A ";
LOCATE 13,8
PRINT " G ";
LOCATE 13,12
PRINT "╠╠╠";
LOCATE 13,18
PRINT " D ";
LOCATE 13,22
PRINT " U ";
LOCATE 13,26
PRINT " O ";
LOCATE 13,32
PRINT " N ";
LOCATE 13,40
PRINT " E ";
LOCATE 13,46
PRINT " L ";
LOCATE 13,64
PRINT " R ";
LOCATE 15,8
PRINT " E ";
LOCATE 15,12
PRINT " N ";
LOCATE 15,18
PRINT " O ";
LOCATE 15,24
PRINT " A ";
LOCATE 15,32
PRINT " I ";
LOCATE 15,40
PRINT " B ";
LOCATE 15,46
PRINT " A ";
LOCATE 15,64
PRINT " Z ";
LOCATE 17,8
PRINT " N ";
LOCATE 17,12
PRINT " O ";
LOCATE 17,18
PRINT " S ";
LOCATE 17,26
PRINT " E ";
LOCATE 17,32
PRINT " A ";
LOCATE 17,36
PRINT " R ";
LOCATE 17,40
PRINT " A ";
LOCATE 17,46
PRINT " R ";
LOCATE 17,50
PRINT " E ";
LOCATE 17,54
PRINT " O ";
LOCATE 17,60
PRINT " R ";
LOCATE 17,64
PRINT " A ";
LOCATE 17,68
PRINT " S ";
LOCATE 19,8
PRINT " O ";
LOCATE 19,12
PRINT " L ";
LOCATE 21,8
PRINT " M ";
LOCATE 21,12
PRINT " O ";
LOCATE 21,16
PRINT " M ";
LOCATE 21,20
PRINT " I ";
LOCATE 21,24
PRINT " A ";
LOCATE 21,28
PRINT "╠╠╠";
LOCATE 21,32
PRINT " U ";
LOCATE 21,36
PRINT " S ";
LOCATE 21,40
PRINT " U ";
LOCATE 21,44
PRINT " R ";
LOCATE 21,48
PRINT " P ";
LOCATE 21,52
PRINT " A ";
LOCATE 21,56
PRINT "╠╠╠";
LOCATE 21,60
PRINT " T ";
LOCATE 21,64
PRINT " I ";
LOCATE 21,68
PRINT " C ";
LOCATE 23,8
PRINT " A ";
LOCATE 23,12
PRINT " C ";
LOCATE 23,16
PRINT " E ";
LOCATE 23,20
PRINT " T ";
LOCATE 23,24
PRINT " I ";
LOCATE 23,28
PRINT " L ";
LOCATE 23,32
PRINT " S ";
LOCATE 23,36
PRINT " A ";
LOCATE 23,40
PRINT " L ";
LOCATE 23,44
PRINT " I ";
LOCATE 23,48
PRINT " C ";
LOCATE 23,52
PRINT " I ";
LOCATE 23,56
PRINT " L ";
LOCATE 23,60
PRINT " I ";
LOCATE 23,64
PRINT " C ";
LOCATE 23,68
PRINT " O ";

CALL SONIDO

REM   E-Screen  Ver 2.10    por  Esteve Valent║ Morales
REM   Nombre de la Pantalla ...: A:\E-SCREEN\PANTALLA\CRUCI007.TUB
LOCATE 2,42
COLOR 15,0
PRINT "здддддддддддддддддддддддддд©";
LOCATE 3,42
PRINT "Ё";
LOCATE 3,44
COLOR 7,0
PRINT "El Editor de Crucigramas";
LOCATE 3,69
COLOR 15,0
PRINT "Ё";
LOCATE 4,42
PRINT "Ё";
LOCATE 4,50
COLOR 7,0
PRINT "versi╒n 1.00";
LOCATE 4,69
COLOR 15,0
PRINT "Ё";
LOCATE 5,42
PRINT "Ё";
LOCATE 5,54
COLOR 7,0
PRINT "por";
LOCATE 5,69
COLOR 15,0
PRINT "Ё";
LOCATE 6,42
PRINT "Ё";
LOCATE 6,45
COLOR 7,0
PRINT "Esteve Valent║ Morales";
LOCATE 6,69
COLOR 15,0
PRINT "Ё";
LOCATE 7,42
PRINT "юдддддддддддддддддддддддддды";

DELAY M%

DO
 A$ = INKEY$

LOCATE 12,18
PRINT "здддддддддддддддддддддддддддддддддддддд©";
LOCATE 13,18
PRINT "Ё";
LOCATE 13,19
COLOR 31,0
PRINT "  Pulsa   I N T R O   para continuar  ";
LOCATE 13,57
COLOR 15,0
PRINT "Ё";
LOCATE 14,18
PRINT "юдддддддддддддддддддддддддддддддддддддды";
LOOP UNTIL A$ = CHR$(&H0D)

CLS
